export const GET_API_DATA = "GET_API_DATA";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const DELETE_CIUDAD = "DELETE_CIUDAD";
export const ADD_CIUDAD_FAVORITA = 'ADD_CIUDAD_FAVORITA';
export const REMOVE_CIUDAD_FAVORITA = 'REMOVE_CIUDAD_FAVORITA';